# fly.toml app configuration file for plex-deeper-queue workers
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "plex-deeper-queue"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.workers"

[env]
  NODE_ENV = "production"
  PORT = "3001"

# Process groups for queue workers
[[processes]]
  name = "app"
  cmd = ["npm", "run", "start:worker"]

# Machine configuration optimized for background workers
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Health check endpoint (optional for workers)
[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
