import type { Metadata } from "next";
import { geistSans, geistMono } from "@/lib/fonts";
import "./globals.css";
import { Providers } from "./providers";
import { ModeToggle } from "@/src/components/theme-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main className="w-full h-screen">
            <Providers>
              <ModeToggle />
              {children}
            </Providers>
          </main>
        </body>
      </html>
    </>
  );
}
